### ISSUE TITLE
Spinner improvement

### ISSUE THREAD

**Issue by cvgarciarea** [cristian99garcia/cedit-activity#4]
These toolbar spinner aren't user friendly at all, imagine you currently are in the number 23 and you want go to 78, you must do 55 clicks! The user should be able to click at the number label and edit it manually.

![Right line spinner](https://s14.postimg.org/e3erjcvz5/Screenshot_20171223_151849.png)
![Font size spinner](https://s14.postimg.org/eu7hpgj0h/Screenshot_20171223_152938.png)

**Comment by sanatankc** [comment]
I think it will be great for Right Line.

But what are your plans about font-size.

Currently it does allows only for font-size `8, 9, 11, 12, 18, 24, 36, 48, 72`. What if user types anything else than that? How are we going to handle this?

**Comment by cvgarciarea** [comment]
No problem if the user set a custom value (in a 8 to 72 range).
If the user set a larger value than 72, it must be set to 72, and if the user set a smaller value than 8, set it to 8.

**Comment by sanatankc** [comment]
Got it.

**Comment by cvgarciarea** [comment]
Fixed in #5
